// Generated by gir (https://github.com/gtk-rs/gir @ 2358cc24efd2)
// from ../../gir-files (@ eab91ba8f88b)
// from ../../xrd-gir-files (@ 2f1ef32fd867)
// DO NOT EDIT

#![cfg(target_os = "linux")]

use xrd_sys::*;
use std::mem::{align_of, size_of};
use std::env;
use std::error::Error;
use std::ffi::OsString;
use std::path::Path;
use std::process::Command;
use std::str;
use tempfile::Builder;

static PACKAGES: &[&str] = &["g3k-0.16"];

#[derive(Clone, Debug)]
struct Compiler {
    pub args: Vec<String>,
}

impl Compiler {
    pub fn new() -> Result<Self, Box<dyn Error>> {
        let mut args = get_var("CC", "cc")?;
        args.push("-Wno-deprecated-declarations".to_owned());
        // For _Generic
        args.push("-std=c11".to_owned());
        // For %z support in printf when using MinGW.
        args.push("-D__USE_MINGW_ANSI_STDIO".to_owned());
        args.extend(get_var("CFLAGS", "")?);
        args.extend(get_var("CPPFLAGS", "")?);
        args.extend(pkg_config_cflags(PACKAGES)?);
        Ok(Self { args })
    }

    pub fn compile(&self, src: &Path, out: &Path) -> Result<(), Box<dyn Error>> {
        let mut cmd = self.to_command();
        cmd.arg(src);
        cmd.arg("-o");
        cmd.arg(out);
        let status = cmd.spawn()?.wait()?;
        if !status.success() {
            return Err(format!("compilation command {cmd:?} failed, {status}").into());
        }
        Ok(())
    }

    fn to_command(&self) -> Command {
        let mut cmd = Command::new(&self.args[0]);
        cmd.args(&self.args[1..]);
        cmd
    }
}

fn get_var(name: &str, default: &str) -> Result<Vec<String>, Box<dyn Error>> {
    match env::var(name) {
        Ok(value) => Ok(shell_words::split(&value)?),
        Err(env::VarError::NotPresent) => Ok(shell_words::split(default)?),
        Err(err) => Err(format!("{name} {err}").into()),
    }
}

fn pkg_config_cflags(packages: &[&str]) -> Result<Vec<String>, Box<dyn Error>> {
    if packages.is_empty() {
        return Ok(Vec::new());
    }
    let pkg_config = env::var_os("PKG_CONFIG")
        .unwrap_or_else(|| OsString::from("pkg-config"));
    let mut cmd = Command::new(pkg_config);
    cmd.arg("--cflags");
    cmd.args(packages);
    let out = cmd.output()?;
    if !out.status.success() {
        return Err(format!("command {cmd:?} returned {}", out.status).into());
    }
    let stdout = str::from_utf8(&out.stdout)?;
    Ok(shell_words::split(stdout.trim())?)
}


#[derive(Copy, Clone, Debug, Eq, PartialEq)]
struct Layout {
    size: usize,
    alignment: usize,
}

#[derive(Copy, Clone, Debug, Default, Eq, PartialEq)]
struct Results {
    /// Number of successfully completed tests.
    passed: usize,
    /// Total number of failed tests (including those that failed to compile).
    failed: usize,
}

impl Results {
    fn record_passed(&mut self) {
        self.passed += 1;
    }
    fn record_failed(&mut self) {
        self.failed += 1;
    }
    fn summary(&self) -> String {
        format!("{} passed; {} failed", self.passed, self.failed)
    }
    fn expect_total_success(&self) {
        if self.failed == 0 {
            println!("OK: {}", self.summary());
        } else {
            panic!("FAILED: {}", self.summary());
        };
    }
}

#[test]
fn cross_validate_constants_with_c() {
    let mut c_constants: Vec<(String, String)> = Vec::new();

    for l in get_c_output("constant").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing ';' separator");
        c_constants.push((name.to_owned(), value.to_owned()));
    }

    let mut results = Results::default();

    for ((rust_name, rust_value), (c_name, c_value)) in
        RUST_CONSTANTS.iter().zip(c_constants.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_value != c_value {
            results.record_failed();
            eprintln!(
                "Constant value mismatch for {rust_name}\nRust: {rust_value:?}\nC:    {c_value:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

#[test]
fn cross_validate_layout_with_c() {
    let mut c_layouts = Vec::new();

    for l in get_c_output("layout").unwrap().lines() {
        let (name, value) = l.split_once(';').expect("Missing first ';' separator");
        let (size, alignment) = value.split_once(';').expect("Missing second ';' separator");
        let size = size.parse().expect("Failed to parse size");
        let alignment = alignment.parse().expect("Failed to parse alignment");
        c_layouts.push((name.to_owned(), Layout { size, alignment }));
    }

    let mut results = Results::default();

    for ((rust_name, rust_layout), (c_name, c_layout)) in
        RUST_LAYOUTS.iter().zip(c_layouts.iter())
    {
        if rust_name != c_name {
            results.record_failed();
            eprintln!("Name mismatch:\nRust: {rust_name:?}\nC:    {c_name:?}");
            continue;
        }

        if rust_layout != c_layout {
            results.record_failed();
            eprintln!(
                "Layout mismatch for {rust_name}\nRust: {rust_layout:?}\nC:    {c_layout:?}",
            );
            continue;
        }

        results.record_passed();
    }

    results.expect_total_success();
}

fn get_c_output(name: &str) -> Result<String, Box<dyn Error>> {
    let tmpdir = Builder::new().prefix("abi").tempdir()?;
    let exe = tmpdir.path().join(name);
    let c_file = Path::new("tests").join(name).with_extension("c");

    let cc = Compiler::new().expect("configured compiler");
    cc.compile(&c_file, &exe)?;

    let mut abi_cmd = Command::new(exe);
    let output = abi_cmd.output()?;
    if !output.status.success() {
        return Err(format!("command {abi_cmd:?} failed, {output:?}").into());
    }

    Ok(String::from_utf8(output.stdout)?)
}

const RUST_LAYOUTS: &[(&str, Layout)] = &[
    ("G3kAccessor", Layout {size: size_of::<G3kAccessor>(), alignment: align_of::<G3kAccessor>()}),
    ("G3kAttributeArray", Layout {size: size_of::<G3kAttributeArray>(), alignment: align_of::<G3kAttributeArray>()}),
    ("G3kAttributeType", Layout {size: size_of::<G3kAttributeType>(), alignment: align_of::<G3kAttributeType>()}),
    ("G3kBackgroundClass", Layout {size: size_of::<G3kBackgroundClass>(), alignment: align_of::<G3kBackgroundClass>()}),
    ("G3kButton", Layout {size: size_of::<G3kButton>(), alignment: align_of::<G3kButton>()}),
    ("G3kButtonClass", Layout {size: size_of::<G3kButtonClass>(), alignment: align_of::<G3kButtonClass>()}),
    ("G3kContainerAttachment", Layout {size: size_of::<G3kContainerAttachment>(), alignment: align_of::<G3kContainerAttachment>()}),
    ("G3kContainerClass", Layout {size: size_of::<G3kContainerClass>(), alignment: align_of::<G3kContainerClass>()}),
    ("G3kContainerLayout", Layout {size: size_of::<G3kContainerLayout>(), alignment: align_of::<G3kContainerLayout>()}),
    ("G3kContextClass", Layout {size: size_of::<G3kContextClass>(), alignment: align_of::<G3kContextClass>()}),
    ("G3kControllerClass", Layout {size: size_of::<G3kControllerClass>(), alignment: align_of::<G3kControllerClass>()}),
    ("G3kCursorClass", Layout {size: size_of::<G3kCursorClass>(), alignment: align_of::<G3kCursorClass>()}),
    ("G3kGrabEvent", Layout {size: size_of::<G3kGrabEvent>(), alignment: align_of::<G3kGrabEvent>()}),
    ("G3kGrabState", Layout {size: size_of::<G3kGrabState>(), alignment: align_of::<G3kGrabState>()}),
    ("G3kHoverEvent", Layout {size: size_of::<G3kHoverEvent>(), alignment: align_of::<G3kHoverEvent>()}),
    ("G3kHoverMode", Layout {size: size_of::<G3kHoverMode>(), alignment: align_of::<G3kHoverMode>()}),
    ("G3kHoverState", Layout {size: size_of::<G3kHoverState>(), alignment: align_of::<G3kHoverState>()}),
    ("G3kInteractionFlags", Layout {size: size_of::<G3kInteractionFlags>(), alignment: align_of::<G3kInteractionFlags>()}),
    ("G3kKeyEvent", Layout {size: size_of::<G3kKeyEvent>(), alignment: align_of::<G3kKeyEvent>()}),
    ("G3kKeyboardButtonClass", Layout {size: size_of::<G3kKeyboardButtonClass>(), alignment: align_of::<G3kKeyboardButtonClass>()}),
    ("G3kKeyboardClass", Layout {size: size_of::<G3kKeyboardClass>(), alignment: align_of::<G3kKeyboardClass>()}),
    ("G3kLoader", Layout {size: size_of::<G3kLoader>(), alignment: align_of::<G3kLoader>()}),
    ("G3kLoaderClass", Layout {size: size_of::<G3kLoaderClass>(), alignment: align_of::<G3kLoaderClass>()}),
    ("G3kLoaderError", Layout {size: size_of::<G3kLoaderError>(), alignment: align_of::<G3kLoaderError>()}),
    ("G3kMaterial", Layout {size: size_of::<G3kMaterial>(), alignment: align_of::<G3kMaterial>()}),
    ("G3kMaterialClass", Layout {size: size_of::<G3kMaterialClass>(), alignment: align_of::<G3kMaterialClass>()}),
    ("G3kMesh", Layout {size: size_of::<G3kMesh>(), alignment: align_of::<G3kMesh>()}),
    ("G3kMeshClass", Layout {size: size_of::<G3kMeshClass>(), alignment: align_of::<G3kMeshClass>()}),
    ("G3kModelClass", Layout {size: size_of::<G3kModelClass>(), alignment: align_of::<G3kModelClass>()}),
    ("G3kNoHoverEvent", Layout {size: size_of::<G3kNoHoverEvent>(), alignment: align_of::<G3kNoHoverEvent>()}),
    ("G3kObject", Layout {size: size_of::<G3kObject>(), alignment: align_of::<G3kObject>()}),
    ("G3kObjectClass", Layout {size: size_of::<G3kObjectClass>(), alignment: align_of::<G3kObjectClass>()}),
    ("G3kObjectManagerClass", Layout {size: size_of::<G3kObjectManagerClass>(), alignment: align_of::<G3kObjectManagerClass>()}),
    ("G3kPipelineClass", Layout {size: size_of::<G3kPipelineClass>(), alignment: align_of::<G3kPipelineClass>()}),
    ("G3kPlane", Layout {size: size_of::<G3kPlane>(), alignment: align_of::<G3kPlane>()}),
    ("G3kPlaneClass", Layout {size: size_of::<G3kPlaneClass>(), alignment: align_of::<G3kPlaneClass>()}),
    ("G3kPlaneUniformBuffer", Layout {size: size_of::<G3kPlaneUniformBuffer>(), alignment: align_of::<G3kPlaneUniformBuffer>()}),
    ("G3kPose", Layout {size: size_of::<G3kPose>(), alignment: align_of::<G3kPose>()}),
    ("G3kPrimitiveClass", Layout {size: size_of::<G3kPrimitiveClass>(), alignment: align_of::<G3kPrimitiveClass>()}),
    ("G3kRayClass", Layout {size: size_of::<G3kRayClass>(), alignment: align_of::<G3kRayClass>()}),
    ("G3kRenderEvent", Layout {size: size_of::<G3kRenderEvent>(), alignment: align_of::<G3kRenderEvent>()}),
    ("G3kRenderEventType", Layout {size: size_of::<G3kRenderEventType>(), alignment: align_of::<G3kRenderEventType>()}),
    ("G3kRendererClass", Layout {size: size_of::<G3kRendererClass>(), alignment: align_of::<G3kRendererClass>()}),
    ("G3kSamplerClass", Layout {size: size_of::<G3kSamplerClass>(), alignment: align_of::<G3kSamplerClass>()}),
    ("G3kSelectionClass", Layout {size: size_of::<G3kSelectionClass>(), alignment: align_of::<G3kSelectionClass>()}),
    ("G3kTipClass", Layout {size: size_of::<G3kTipClass>(), alignment: align_of::<G3kTipClass>()}),
    ("G3kTransformLock", Layout {size: size_of::<G3kTransformLock>(), alignment: align_of::<G3kTransformLock>()}),
    ("G3kTransformTransition", Layout {size: size_of::<G3kTransformTransition>(), alignment: align_of::<G3kTransformTransition>()}),
];

const RUST_CONSTANTS: &[(&str, &str)] = &[
    ("(gint) G3K_ATTRIBUTE_TYPE_DOUBLE", "0"),
    ("(gint) G3K_ATTRIBUTE_TYPE_FLOAT", "1"),
    ("(gint) G3K_ATTRIBUTE_TYPE_INT16", "5"),
    ("(gint) G3K_ATTRIBUTE_TYPE_INT32", "3"),
    ("(gint) G3K_ATTRIBUTE_TYPE_INT8", "7"),
    ("(gint) G3K_ATTRIBUTE_TYPE_UINT16", "4"),
    ("(gint) G3K_ATTRIBUTE_TYPE_UINT32", "2"),
    ("(gint) G3K_ATTRIBUTE_TYPE_UINT8", "6"),
    ("(gint) G3K_CONTAINER_ATTACHMENT_HAND", "2"),
    ("(gint) G3K_CONTAINER_ATTACHMENT_HEAD", "1"),
    ("(gint) G3K_CONTAINER_ATTACHMENT_NONE", "0"),
    ("(gint) G3K_CONTAINER_HORIZONTAL", "1"),
    ("(gint) G3K_CONTAINER_NO_LAYOUT", "0"),
    ("(gint) G3K_CONTAINER_RELATIVE", "3"),
    ("(gint) G3K_CONTAINER_VERTICAL", "2"),
    ("(gint) G3K_HOVER_MODE_BUTTONS", "1"),
    ("(gint) G3K_HOVER_MODE_EVERYTHING", "0"),
    ("(guint) G3K_INTERACTION_BUTTON", "16"),
    ("(guint) G3K_INTERACTION_DESTROY_WITH_PARENT", "8"),
    ("(guint) G3K_INTERACTION_DRAGGABLE", "2"),
    ("(guint) G3K_INTERACTION_HOVERABLE", "1"),
    ("(guint) G3K_INTERACTION_MANAGED", "4"),
    ("(gint) G3K_LOADER_ERROR_FAIL", "0"),
    ("(gint) G3K_RENDER_EVENT_FRAME_END", "1"),
    ("(gint) G3K_RENDER_EVENT_FRAME_START", "0"),
    ("(gint) XRD_TRANSFORM_LOCK_NONE", "0"),
    ("(gint) XRD_TRANSFORM_LOCK_PUSH_PULL", "1"),
    ("(gint) XRD_TRANSFORM_LOCK_SCALE", "2"),
];


