// Generated by gir (https://github.com/gtk-rs/gir @ 2358cc24efd2)
// from ../../gir-files (@ eab91ba8f88b)
// from ../../xrd-gir-files (@ 2f1ef32fd867)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "G3kAccessor", sizeof(G3kAccessor), alignof(G3kAccessor));
    printf("%s;%zu;%zu\n", "G3kAttributeArray", sizeof(G3kAttributeArray), alignof(G3kAttributeArray));
    printf("%s;%zu;%zu\n", "G3kAttributeType", sizeof(G3kAttributeType), alignof(G3kAttributeType));
    printf("%s;%zu;%zu\n", "G3kBackgroundClass", sizeof(G3kBackgroundClass), alignof(G3kBackgroundClass));
    printf("%s;%zu;%zu\n", "G3kButton", sizeof(G3kButton), alignof(G3kButton));
    printf("%s;%zu;%zu\n", "G3kButtonClass", sizeof(G3kButtonClass), alignof(G3kButtonClass));
    printf("%s;%zu;%zu\n", "G3kContainerAttachment", sizeof(G3kContainerAttachment), alignof(G3kContainerAttachment));
    printf("%s;%zu;%zu\n", "G3kContainerClass", sizeof(G3kContainerClass), alignof(G3kContainerClass));
    printf("%s;%zu;%zu\n", "G3kContainerLayout", sizeof(G3kContainerLayout), alignof(G3kContainerLayout));
    printf("%s;%zu;%zu\n", "G3kContextClass", sizeof(G3kContextClass), alignof(G3kContextClass));
    printf("%s;%zu;%zu\n", "G3kControllerClass", sizeof(G3kControllerClass), alignof(G3kControllerClass));
    printf("%s;%zu;%zu\n", "G3kCursorClass", sizeof(G3kCursorClass), alignof(G3kCursorClass));
    printf("%s;%zu;%zu\n", "G3kGrabEvent", sizeof(G3kGrabEvent), alignof(G3kGrabEvent));
    printf("%s;%zu;%zu\n", "G3kGrabState", sizeof(G3kGrabState), alignof(G3kGrabState));
    printf("%s;%zu;%zu\n", "G3kHoverEvent", sizeof(G3kHoverEvent), alignof(G3kHoverEvent));
    printf("%s;%zu;%zu\n", "G3kHoverMode", sizeof(G3kHoverMode), alignof(G3kHoverMode));
    printf("%s;%zu;%zu\n", "G3kHoverState", sizeof(G3kHoverState), alignof(G3kHoverState));
    printf("%s;%zu;%zu\n", "G3kInteractionFlags", sizeof(G3kInteractionFlags), alignof(G3kInteractionFlags));
    printf("%s;%zu;%zu\n", "G3kKeyEvent", sizeof(G3kKeyEvent), alignof(G3kKeyEvent));
    printf("%s;%zu;%zu\n", "G3kKeyboardButtonClass", sizeof(G3kKeyboardButtonClass), alignof(G3kKeyboardButtonClass));
    printf("%s;%zu;%zu\n", "G3kKeyboardClass", sizeof(G3kKeyboardClass), alignof(G3kKeyboardClass));
    printf("%s;%zu;%zu\n", "G3kLoader", sizeof(G3kLoader), alignof(G3kLoader));
    printf("%s;%zu;%zu\n", "G3kLoaderClass", sizeof(G3kLoaderClass), alignof(G3kLoaderClass));
    printf("%s;%zu;%zu\n", "G3kLoaderError", sizeof(G3kLoaderError), alignof(G3kLoaderError));
    printf("%s;%zu;%zu\n", "G3kMaterial", sizeof(G3kMaterial), alignof(G3kMaterial));
    printf("%s;%zu;%zu\n", "G3kMaterialClass", sizeof(G3kMaterialClass), alignof(G3kMaterialClass));
    printf("%s;%zu;%zu\n", "G3kMesh", sizeof(G3kMesh), alignof(G3kMesh));
    printf("%s;%zu;%zu\n", "G3kMeshClass", sizeof(G3kMeshClass), alignof(G3kMeshClass));
    printf("%s;%zu;%zu\n", "G3kModelClass", sizeof(G3kModelClass), alignof(G3kModelClass));
    printf("%s;%zu;%zu\n", "G3kNoHoverEvent", sizeof(G3kNoHoverEvent), alignof(G3kNoHoverEvent));
    printf("%s;%zu;%zu\n", "G3kObject", sizeof(G3kObject), alignof(G3kObject));
    printf("%s;%zu;%zu\n", "G3kObjectClass", sizeof(G3kObjectClass), alignof(G3kObjectClass));
    printf("%s;%zu;%zu\n", "G3kObjectManagerClass", sizeof(G3kObjectManagerClass), alignof(G3kObjectManagerClass));
    printf("%s;%zu;%zu\n", "G3kPipelineClass", sizeof(G3kPipelineClass), alignof(G3kPipelineClass));
    printf("%s;%zu;%zu\n", "G3kPlane", sizeof(G3kPlane), alignof(G3kPlane));
    printf("%s;%zu;%zu\n", "G3kPlaneClass", sizeof(G3kPlaneClass), alignof(G3kPlaneClass));
    printf("%s;%zu;%zu\n", "G3kPlaneUniformBuffer", sizeof(G3kPlaneUniformBuffer), alignof(G3kPlaneUniformBuffer));
    printf("%s;%zu;%zu\n", "G3kPose", sizeof(G3kPose), alignof(G3kPose));
    printf("%s;%zu;%zu\n", "G3kPrimitiveClass", sizeof(G3kPrimitiveClass), alignof(G3kPrimitiveClass));
    printf("%s;%zu;%zu\n", "G3kRayClass", sizeof(G3kRayClass), alignof(G3kRayClass));
    printf("%s;%zu;%zu\n", "G3kRenderEvent", sizeof(G3kRenderEvent), alignof(G3kRenderEvent));
    printf("%s;%zu;%zu\n", "G3kRenderEventType", sizeof(G3kRenderEventType), alignof(G3kRenderEventType));
    printf("%s;%zu;%zu\n", "G3kRendererClass", sizeof(G3kRendererClass), alignof(G3kRendererClass));
    printf("%s;%zu;%zu\n", "G3kSamplerClass", sizeof(G3kSamplerClass), alignof(G3kSamplerClass));
    printf("%s;%zu;%zu\n", "G3kSelectionClass", sizeof(G3kSelectionClass), alignof(G3kSelectionClass));
    printf("%s;%zu;%zu\n", "G3kTipClass", sizeof(G3kTipClass), alignof(G3kTipClass));
    printf("%s;%zu;%zu\n", "G3kTransformLock", sizeof(G3kTransformLock), alignof(G3kTransformLock));
    printf("%s;%zu;%zu\n", "G3kTransformTransition", sizeof(G3kTransformTransition), alignof(G3kTransformTransition));
    return 0;
}
