// Generated by gir (https://github.com/gtk-rs/gir @ 2358cc24efd2)
// from ../../gir-files (@ eab91ba8f88b)
// from ../../xrd-gir-files (@ 2f1ef32fd867)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) LEFT_BUTTON);
    PRINT_CONSTANT((gint) MIDDLE_BUTTON);
    PRINT_CONSTANT((gint) RIGHT_BUTTON);
    PRINT_CONSTANT((gint) SCROLL_DOWN);
    PRINT_CONSTANT((gint) SCROLL_LEFT);
    PRINT_CONSTANT((gint) SCROLL_RIGHT);
    PRINT_CONSTANT((gint) SCROLL_UP);
    PRINT_CONSTANT(XRD_TIP_VIEWPORT_SCALE);
    return 0;
}
