// Generated by gir (https://github.com/gtk-rs/gir @ 2358cc24efd2)
// from ../../gir-files (@ eab91ba8f88b)
// from ../../xrd-gir-files (@ 3896faadf111)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) LEFT_BUTTON);
    PRINT_CONSTANT((gint) MIDDLE_BUTTON);
    PRINT_CONSTANT((gint) RIGHT_BUTTON);
    PRINT_CONSTANT((gint) SCROLL_DOWN);
    PRINT_CONSTANT((gint) SCROLL_LEFT);
    PRINT_CONSTANT((gint) SCROLL_RIGHT);
    PRINT_CONSTANT((gint) SCROLL_UP);
    PRINT_CONSTANT((gint) XRD_CLIENT_MODE_OVERLAY);
    PRINT_CONSTANT((gint) XRD_CLIENT_MODE_SCENE);
    PRINT_CONSTANT((gint) XRD_CONTAINER_ATTACHMENT_HAND);
    PRINT_CONSTANT((gint) XRD_CONTAINER_ATTACHMENT_HEAD);
    PRINT_CONSTANT((gint) XRD_CONTAINER_ATTACHMENT_NONE);
    PRINT_CONSTANT((gint) XRD_CONTAINER_HORIZONTAL);
    PRINT_CONSTANT((gint) XRD_CONTAINER_NO_LAYOUT);
    PRINT_CONSTANT((gint) XRD_CONTAINER_RELATIVE);
    PRINT_CONSTANT((gint) XRD_CONTAINER_VERTICAL);
    PRINT_CONSTANT((gint) XRD_HOVER_MODE_BUTTONS);
    PRINT_CONSTANT((gint) XRD_HOVER_MODE_EVERYTHING);
    PRINT_CONSTANT(XRD_TIP_APPARENT_SIZE_DISTANCE);
    PRINT_CONSTANT(XRD_TIP_VIEWPORT_SCALE);
    PRINT_CONSTANT((guint) XRD_WINDOW_BUTTON);
    PRINT_CONSTANT((guint) XRD_WINDOW_DESTROY_WITH_PARENT);
    PRINT_CONSTANT((guint) XRD_WINDOW_DRAGGABLE);
    PRINT_CONSTANT((guint) XRD_WINDOW_HOVERABLE);
    PRINT_CONSTANT((guint) XRD_WINDOW_MANAGED);
    return 0;
}
