// Generated by gir (https://github.com/gtk-rs/gir @ 2358cc24efd2)
// from ../../gir-files (@ eab91ba8f88b)
// from ../../xrd-gir-files (@ 2f1ef32fd867)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "XrdClickEvent", sizeof(XrdClickEvent), alignof(XrdClickEvent));
    printf("%s;%zu;%zu\n", "XrdInputSynthButton", sizeof(XrdInputSynthButton), alignof(XrdInputSynthButton));
    printf("%s;%zu;%zu\n", "XrdInputSynthClass", sizeof(XrdInputSynthClass), alignof(XrdInputSynthClass));
    printf("%s;%zu;%zu\n", "XrdMoveCursorEvent", sizeof(XrdMoveCursorEvent), alignof(XrdMoveCursorEvent));
    printf("%s;%zu;%zu\n", "XrdShakeCompensatorClass", sizeof(XrdShakeCompensatorClass), alignof(XrdShakeCompensatorClass));
    printf("%s;%zu;%zu\n", "XrdShellClass", sizeof(XrdShellClass), alignof(XrdShellClass));
    printf("%s;%zu;%zu\n", "XrdWindowClass", sizeof(XrdWindowClass), alignof(XrdWindowClass));
    printf("%s;%zu;%zu\n", "XrdWindowRect", sizeof(XrdWindowRect), alignof(XrdWindowRect));
    printf("%s;%zu;%zu\n", "XrdWindowRectPoint", sizeof(XrdWindowRectPoint), alignof(XrdWindowRectPoint));
    return 0;
}
