// Generated by gir (https://github.com/gtk-rs/gir @ e0d8d8d645b1)
// from ../../gir-files (@ 54ae87ae2ece+)
// from ../../xrd-gir-files (@ 8cffc8b155f9)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "XrdClickEvent", sizeof(XrdClickEvent), alignof(XrdClickEvent));
    printf("%s;%zu;%zu\n", "XrdClient", sizeof(XrdClient), alignof(XrdClient));
    printf("%s;%zu;%zu\n", "XrdClientClass", sizeof(XrdClientClass), alignof(XrdClientClass));
    printf("%s;%zu;%zu\n", "XrdClientMode", sizeof(XrdClientMode), alignof(XrdClientMode));
    printf("%s;%zu;%zu\n", "XrdContainerAttachment", sizeof(XrdContainerAttachment), alignof(XrdContainerAttachment));
    printf("%s;%zu;%zu\n", "XrdContainerClass", sizeof(XrdContainerClass), alignof(XrdContainerClass));
    printf("%s;%zu;%zu\n", "XrdContainerLayout", sizeof(XrdContainerLayout), alignof(XrdContainerLayout));
    printf("%s;%zu;%zu\n", "XrdDesktopCursorData", sizeof(XrdDesktopCursorData), alignof(XrdDesktopCursorData));
    printf("%s;%zu;%zu\n", "XrdDesktopCursorInterface", sizeof(XrdDesktopCursorInterface), alignof(XrdDesktopCursorInterface));
    printf("%s;%zu;%zu\n", "XrdGrabEvent", sizeof(XrdGrabEvent), alignof(XrdGrabEvent));
    printf("%s;%zu;%zu\n", "XrdHoverEvent", sizeof(XrdHoverEvent), alignof(XrdHoverEvent));
    printf("%s;%zu;%zu\n", "XrdHoverMode", sizeof(XrdHoverMode), alignof(XrdHoverMode));
    printf("%s;%zu;%zu\n", "XrdInputSynthButton", sizeof(XrdInputSynthButton), alignof(XrdInputSynthButton));
    printf("%s;%zu;%zu\n", "XrdInputSynthClass", sizeof(XrdInputSynthClass), alignof(XrdInputSynthClass));
    printf("%s;%zu;%zu\n", "XrdMoveCursorEvent", sizeof(XrdMoveCursorEvent), alignof(XrdMoveCursorEvent));
    printf("%s;%zu;%zu\n", "XrdNoHoverEvent", sizeof(XrdNoHoverEvent), alignof(XrdNoHoverEvent));
    printf("%s;%zu;%zu\n", "XrdShakeCompensatorClass", sizeof(XrdShakeCompensatorClass), alignof(XrdShakeCompensatorClass));
    printf("%s;%zu;%zu\n", "XrdTransformTransition", sizeof(XrdTransformTransition), alignof(XrdTransformTransition));
    printf("%s;%zu;%zu\n", "XrdWindowData", sizeof(XrdWindowData), alignof(XrdWindowData));
    printf("%s;%zu;%zu\n", "XrdWindowFlags", sizeof(XrdWindowFlags), alignof(XrdWindowFlags));
    printf("%s;%zu;%zu\n", "XrdWindowInterface", sizeof(XrdWindowInterface), alignof(XrdWindowInterface));
    printf("%s;%zu;%zu\n", "XrdWindowManagerClass", sizeof(XrdWindowManagerClass), alignof(XrdWindowManagerClass));
    return 0;
}
