// Generated by gir (https://github.com/gtk-rs/gir @ e0d8d8d645b1)
// from ../gir-files (@ 54ae87ae2ece)
// from ../xrd-gir-files (@ 8cffc8b155f9)
// DO NOT EDIT

#include "manual.h"
#include <stdio.h>

#define PRINT_CONSTANT(CONSTANT_NAME) \
    printf("%s;", #CONSTANT_NAME); \
    printf(_Generic((CONSTANT_NAME), \
                    char *: "%s", \
                    const char *: "%s", \
                    char: "%c", \
                    signed char: "%hhd", \
                    unsigned char: "%hhu", \
                    short int: "%hd", \
                    unsigned short int: "%hu", \
                    int: "%d", \
                    unsigned int: "%u", \
                    long: "%ld", \
                    unsigned long: "%lu", \
                    long long: "%lld", \
                    unsigned long long: "%llu", \
                    float: "%f", \
                    double: "%f", \
                    long double: "%ld"), \
           CONSTANT_NAME); \
    printf("\n");

int main() {
    PRINT_CONSTANT((gint) GXR_ACTION_DIGITAL);
    PRINT_CONSTANT((gint) GXR_ACTION_DIGITAL_FROM_FLOAT);
    PRINT_CONSTANT((gint) GXR_ACTION_FLOAT);
    PRINT_CONSTANT((gint) GXR_ACTION_HAPTIC);
    PRINT_CONSTANT((gint) GXR_ACTION_POSE);
    PRINT_CONSTANT((gint) GXR_ACTION_VEC2F);
    PRINT_CONSTANT((gint) GXR_API_NONE);
    PRINT_CONSTANT((gint) GXR_API_OPENVR);
    PRINT_CONSTANT((gint) GXR_API_OPENXR);
    PRINT_CONSTANT((gint) GXR_APP_HEADLESS);
    PRINT_CONSTANT((gint) GXR_APP_OVERLAY);
    PRINT_CONSTANT((gint) GXR_APP_SCENE);
    PRINT_CONSTANT((gint) GXR_BINDING_COMPONENT_CLICK);
    PRINT_CONSTANT((gint) GXR_BINDING_COMPONENT_FORCE);
    PRINT_CONSTANT((gint) GXR_BINDING_COMPONENT_NONE);
    PRINT_CONSTANT((gint) GXR_BINDING_COMPONENT_POSITION);
    PRINT_CONSTANT((gint) GXR_BINDING_COMPONENT_PULL);
    PRINT_CONSTANT((gint) GXR_BINDING_COMPONENT_TOUCH);
    PRINT_CONSTANT((gint) GXR_BINDING_COMPONENT_UNKNOWN);
    PRINT_CONSTANT((gint) GXR_BINDING_MODE_ANALOG_STICK);
    PRINT_CONSTANT((gint) GXR_BINDING_MODE_BUTTON);
    PRINT_CONSTANT((gint) GXR_BINDING_MODE_NONE);
    PRINT_CONSTANT((gint) GXR_BINDING_MODE_TRACKPAD);
    PRINT_CONSTANT((gint) GXR_BINDING_MODE_UNKNOWN);
    PRINT_CONSTANT((gint) GXR_BINDING_TYPE_BOOLEAN);
    PRINT_CONSTANT((gint) GXR_BINDING_TYPE_FLOAT);
    PRINT_CONSTANT((gint) GXR_BINDING_TYPE_HAPTIC);
    PRINT_CONSTANT((gint) GXR_BINDING_TYPE_POSE);
    PRINT_CONSTANT((gint) GXR_BINDING_TYPE_UNKNOWN);
    PRINT_CONSTANT((gint) GXR_BINDING_TYPE_VEC2);
    PRINT_CONSTANT(GXR_DEVICE_INDEX_HMD);
    PRINT_CONSTANT(GXR_DEVICE_INDEX_MAX);
    PRINT_CONSTANT((gint) GXR_EYE_LEFT);
    PRINT_CONSTANT((gint) GXR_EYE_RIGHT);
    PRINT_CONSTANT(GXR_MODEL_NAME_MAX);
    PRINT_CONSTANT((gint) GXR_QUIT_APPLICATION_TRANSITION);
    PRINT_CONSTANT((gint) GXR_QUIT_PROCESS_QUIT);
    PRINT_CONSTANT((gint) GXR_QUIT_SHUTDOWN);
    PRINT_CONSTANT(GXR_TIP_APPARENT_SIZE_DISTANCE);
    PRINT_CONSTANT(GXR_TIP_VIEWPORT_SCALE);
    PRINT_CONSTANT((gint) GXR_TRANSFORM_LOCK_NONE);
    PRINT_CONSTANT((gint) GXR_TRANSFORM_LOCK_PUSH_PULL);
    PRINT_CONSTANT((gint) GXR_TRANSFORM_LOCK_SCALE);
    return 0;
}
