// Generated by gir (https://github.com/gtk-rs/gir @ e0d8d8d645b1)
// from ../gir-files (@ 54ae87ae2ece)
// from ../xrd-gir-files (@ 8cffc8b155f9)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GxrAction", sizeof(GxrAction), alignof(GxrAction));
    printf("%s;%zu;%zu\n", "GxrActionClass", sizeof(GxrActionClass), alignof(GxrActionClass));
    printf("%s;%zu;%zu\n", "GxrActionManifestEntry", sizeof(GxrActionManifestEntry), alignof(GxrActionManifestEntry));
    printf("%s;%zu;%zu\n", "GxrActionSet", sizeof(GxrActionSet), alignof(GxrActionSet));
    printf("%s;%zu;%zu\n", "GxrActionSetClass", sizeof(GxrActionSetClass), alignof(GxrActionSetClass));
    printf("%s;%zu;%zu\n", "GxrActionType", sizeof(GxrActionType), alignof(GxrActionType));
    printf("%s;%zu;%zu\n", "GxrAnalogEvent", sizeof(GxrAnalogEvent), alignof(GxrAnalogEvent));
    printf("%s;%zu;%zu\n", "GxrApi", sizeof(GxrApi), alignof(GxrApi));
    printf("%s;%zu;%zu\n", "GxrAppType", sizeof(GxrAppType), alignof(GxrAppType));
    printf("%s;%zu;%zu\n", "GxrBackendClass", sizeof(GxrBackendClass), alignof(GxrBackendClass));
    printf("%s;%zu;%zu\n", "GxrBinding", sizeof(GxrBinding), alignof(GxrBinding));
    printf("%s;%zu;%zu\n", "GxrBindingComponent", sizeof(GxrBindingComponent), alignof(GxrBindingComponent));
    printf("%s;%zu;%zu\n", "GxrBindingManifest", sizeof(GxrBindingManifest), alignof(GxrBindingManifest));
    printf("%s;%zu;%zu\n", "GxrBindingMode", sizeof(GxrBindingMode), alignof(GxrBindingMode));
    printf("%s;%zu;%zu\n", "GxrBindingPath", sizeof(GxrBindingPath), alignof(GxrBindingPath));
    printf("%s;%zu;%zu\n", "GxrBindingType", sizeof(GxrBindingType), alignof(GxrBindingType));
    printf("%s;%zu;%zu\n", "GxrContext", sizeof(GxrContext), alignof(GxrContext));
    printf("%s;%zu;%zu\n", "GxrContextClass", sizeof(GxrContextClass), alignof(GxrContextClass));
    printf("%s;%zu;%zu\n", "GxrControllerClass", sizeof(GxrControllerClass), alignof(GxrControllerClass));
    printf("%s;%zu;%zu\n", "GxrDevice", sizeof(GxrDevice), alignof(GxrDevice));
    printf("%s;%zu;%zu\n", "GxrDeviceClass", sizeof(GxrDeviceClass), alignof(GxrDeviceClass));
    printf("%s;%zu;%zu\n", "GxrDeviceManagerClass", sizeof(GxrDeviceManagerClass), alignof(GxrDeviceManagerClass));
    printf("%s;%zu;%zu\n", "GxrDigitalEvent", sizeof(GxrDigitalEvent), alignof(GxrDigitalEvent));
    printf("%s;%zu;%zu\n", "GxrEye", sizeof(GxrEye), alignof(GxrEye));
    printf("%s;%zu;%zu\n", "GxrGrabState", sizeof(GxrGrabState), alignof(GxrGrabState));
    printf("%s;%zu;%zu\n", "GxrHoverState", sizeof(GxrHoverState), alignof(GxrHoverState));
    printf("%s;%zu;%zu\n", "GxrManifestClass", sizeof(GxrManifestClass), alignof(GxrManifestClass));
    printf("%s;%zu;%zu\n", "GxrModelInterface", sizeof(GxrModelInterface), alignof(GxrModelInterface));
    printf("%s;%zu;%zu\n", "GxrOverlay", sizeof(GxrOverlay), alignof(GxrOverlay));
    printf("%s;%zu;%zu\n", "GxrOverlayClass", sizeof(GxrOverlayClass), alignof(GxrOverlayClass));
    printf("%s;%zu;%zu\n", "GxrPointerData", sizeof(GxrPointerData), alignof(GxrPointerData));
    printf("%s;%zu;%zu\n", "GxrPointerInterface", sizeof(GxrPointerInterface), alignof(GxrPointerInterface));
    printf("%s;%zu;%zu\n", "GxrPointerTipAnimation", sizeof(GxrPointerTipAnimation), alignof(GxrPointerTipAnimation));
    printf("%s;%zu;%zu\n", "GxrPointerTipData", sizeof(GxrPointerTipData), alignof(GxrPointerTipData));
    printf("%s;%zu;%zu\n", "GxrPointerTipInterface", sizeof(GxrPointerTipInterface), alignof(GxrPointerTipInterface));
    printf("%s;%zu;%zu\n", "GxrPointerTipSettings", sizeof(GxrPointerTipSettings), alignof(GxrPointerTipSettings));
    printf("%s;%zu;%zu\n", "GxrPose", sizeof(GxrPose), alignof(GxrPose));
    printf("%s;%zu;%zu\n", "GxrPoseEvent", sizeof(GxrPoseEvent), alignof(GxrPoseEvent));
    printf("%s;%zu;%zu\n", "GxrQuitEvent", sizeof(GxrQuitEvent), alignof(GxrQuitEvent));
    printf("%s;%zu;%zu\n", "GxrQuitReason", sizeof(GxrQuitReason), alignof(GxrQuitReason));
    printf("%s;%zu;%zu\n", "GxrTransformLock", sizeof(GxrTransformLock), alignof(GxrTransformLock));
    return 0;
}
