// Generated by gir (https://github.com/gtk-rs/gir @ e0d8d8d645b1)
// from ../gir-files (@ 54ae87ae2ece+)
// from ../xrd-gir-files (@ 8cffc8b155f9)
// DO NOT EDIT

mod client;
pub use self::client::Client;

#[doc(hidden)]
pub mod traits {
    pub use super::client::ClientExt;
}
