// Generated by gir (https://github.com/gtk-rs/gir @ 2358cc24efd2)
// from ../gir-files (@ eab91ba8f88b)
// from ../xrd-gir-files (@ 2f1ef32fd867)
// DO NOT EDIT

mod texture;
pub use self::texture::Texture;

