// Generated by gir (https://github.com/gtk-rs/gir @ 2358cc24efd2)
// from ../gir-files (@ eab91ba8f88b)
// from ../xrd-gir-files (@ 3896faadf111)
// DO NOT EDIT

mod client;
pub use self::client::Client;

mod texture;
pub use self::texture::Texture;

#[doc(hidden)]
pub mod traits {
    pub use super::client::ClientExt;
}
