// Generated by gir (https://github.com/gtk-rs/gir @ 2358cc24efd2)
// from ../../gir-files (@ eab91ba8f88b)
// from ../../xrd-gir-files (@ 2f1ef32fd867)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GulkanAxisEvent", sizeof(GulkanAxisEvent), alignof(GulkanAxisEvent));
    printf("%s;%zu;%zu\n", "GulkanBufferClass", sizeof(GulkanBufferClass), alignof(GulkanBufferClass));
    printf("%s;%zu;%zu\n", "GulkanButtonEvent", sizeof(GulkanButtonEvent), alignof(GulkanButtonEvent));
    printf("%s;%zu;%zu\n", "GulkanCmdBufferClass", sizeof(GulkanCmdBufferClass), alignof(GulkanCmdBufferClass));
    printf("%s;%zu;%zu\n", "GulkanContext", sizeof(GulkanContext), alignof(GulkanContext));
    printf("%s;%zu;%zu\n", "GulkanContextClass", sizeof(GulkanContextClass), alignof(GulkanContextClass));
    printf("%s;%zu;%zu\n", "GulkanDescriptorPoolClass", sizeof(GulkanDescriptorPoolClass), alignof(GulkanDescriptorPoolClass));
    printf("%s;%zu;%zu\n", "GulkanDescriptorSetClass", sizeof(GulkanDescriptorSetClass), alignof(GulkanDescriptorSetClass));
    printf("%s;%zu;%zu\n", "GulkanDeviceClass", sizeof(GulkanDeviceClass), alignof(GulkanDeviceClass));
    printf("%s;%zu;%zu\n", "GulkanDmabufAttributes", sizeof(GulkanDmabufAttributes), alignof(GulkanDmabufAttributes));
    printf("%s;%zu;%zu\n", "GulkanFrameBufferClass", sizeof(GulkanFrameBufferClass), alignof(GulkanFrameBufferClass));
    printf("%s;%zu;%zu\n", "GulkanInstanceClass", sizeof(GulkanInstanceClass), alignof(GulkanInstanceClass));
    printf("%s;%zu;%zu\n", "GulkanKeyEvent", sizeof(GulkanKeyEvent), alignof(GulkanKeyEvent));
    printf("%s;%zu;%zu\n", "GulkanPipelineClass", sizeof(GulkanPipelineClass), alignof(GulkanPipelineClass));
    printf("%s;%zu;%zu\n", "GulkanQueueClass", sizeof(GulkanQueueClass), alignof(GulkanQueueClass));
    printf("%s;%zu;%zu\n", "GulkanRenderPassClass", sizeof(GulkanRenderPassClass), alignof(GulkanRenderPassClass));
    printf("%s;%zu;%zu\n", "GulkanRenderer", sizeof(GulkanRenderer), alignof(GulkanRenderer));
    printf("%s;%zu;%zu\n", "GulkanRendererClass", sizeof(GulkanRendererClass), alignof(GulkanRendererClass));
    printf("%s;%zu;%zu\n", "GulkanSwapchainClass", sizeof(GulkanSwapchainClass), alignof(GulkanSwapchainClass));
    printf("%s;%zu;%zu\n", "GulkanSwapchainRenderer", sizeof(GulkanSwapchainRenderer), alignof(GulkanSwapchainRenderer));
    printf("%s;%zu;%zu\n", "GulkanSwapchainRendererClass", sizeof(GulkanSwapchainRendererClass), alignof(GulkanSwapchainRendererClass));
    printf("%s;%zu;%zu\n", "GulkanTextureClass", sizeof(GulkanTextureClass), alignof(GulkanTextureClass));
    printf("%s;%zu;%zu\n", "GulkanUniformBufferClass", sizeof(GulkanUniformBufferClass), alignof(GulkanUniformBufferClass));
    printf("%s;%zu;%zu\n", "GulkanVertexBufferClass", sizeof(GulkanVertexBufferClass), alignof(GulkanVertexBufferClass));
    printf("%s;%zu;%zu\n", "GulkanWindow", sizeof(GulkanWindow), alignof(GulkanWindow));
    printf("%s;%zu;%zu\n", "GulkanWindowClass", sizeof(GulkanWindowClass), alignof(GulkanWindowClass));
    return 0;
}
