// Generated by gir (https://github.com/gtk-rs/gir @ 2358cc24efd2)
// from ../../gir-files (@ eab91ba8f88b)
// from ../../xrd-gir-files (@ 3896faadf111)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GulkanBufferClass", sizeof(GulkanBufferClass), alignof(GulkanBufferClass));
    printf("%s;%zu;%zu\n", "GulkanClient", sizeof(GulkanClient), alignof(GulkanClient));
    printf("%s;%zu;%zu\n", "GulkanClientClass", sizeof(GulkanClientClass), alignof(GulkanClientClass));
    printf("%s;%zu;%zu\n", "GulkanCmdBufferClass", sizeof(GulkanCmdBufferClass), alignof(GulkanCmdBufferClass));
    printf("%s;%zu;%zu\n", "GulkanDescriptorPoolClass", sizeof(GulkanDescriptorPoolClass), alignof(GulkanDescriptorPoolClass));
    printf("%s;%zu;%zu\n", "GulkanDeviceClass", sizeof(GulkanDeviceClass), alignof(GulkanDeviceClass));
    printf("%s;%zu;%zu\n", "GulkanFrameBufferClass", sizeof(GulkanFrameBufferClass), alignof(GulkanFrameBufferClass));
    printf("%s;%zu;%zu\n", "GulkanInstanceClass", sizeof(GulkanInstanceClass), alignof(GulkanInstanceClass));
    printf("%s;%zu;%zu\n", "GulkanQueueClass", sizeof(GulkanQueueClass), alignof(GulkanQueueClass));
    printf("%s;%zu;%zu\n", "GulkanRenderPassClass", sizeof(GulkanRenderPassClass), alignof(GulkanRenderPassClass));
    printf("%s;%zu;%zu\n", "GulkanRenderer", sizeof(GulkanRenderer), alignof(GulkanRenderer));
    printf("%s;%zu;%zu\n", "GulkanRendererClass", sizeof(GulkanRendererClass), alignof(GulkanRendererClass));
    printf("%s;%zu;%zu\n", "GulkanSwapchainClass", sizeof(GulkanSwapchainClass), alignof(GulkanSwapchainClass));
    printf("%s;%zu;%zu\n", "GulkanSwapchainRenderer", sizeof(GulkanSwapchainRenderer), alignof(GulkanSwapchainRenderer));
    printf("%s;%zu;%zu\n", "GulkanSwapchainRendererClass", sizeof(GulkanSwapchainRendererClass), alignof(GulkanSwapchainRendererClass));
    printf("%s;%zu;%zu\n", "GulkanTextureClass", sizeof(GulkanTextureClass), alignof(GulkanTextureClass));
    printf("%s;%zu;%zu\n", "GulkanUniformBufferClass", sizeof(GulkanUniformBufferClass), alignof(GulkanUniformBufferClass));
    printf("%s;%zu;%zu\n", "GulkanVertexBufferClass", sizeof(GulkanVertexBufferClass), alignof(GulkanVertexBufferClass));
    return 0;
}
