[options]
girs_directories = ["../../gir-files", "../../xrd-gir-files"]
library = "G3k"
version = "0.16"
min_cfg_version = "0.16"
work_mode = "sys"

external_libraries = [ "Gio", "GLib", "GObject", "Graphene", "Gulkan" ]
