[options]
girs_directories = ["../gir-files", "../xrd-gir-files"]
library = "G3k"
version = "0.16"
min_cfg_version = "0.16"
work_mode = "normal"
concurrency = "send"

external_libraries = [ "Gio", "Gdk", "GLib", "GObject", "Graphene", "Gulkan" ]

generate = [
	"Xrd.WindowManager",
	"Xrd.Window",
	"Xrd.Container",
	"Xrd.DesktopCursor",
	"Xrd.ClientMode",
	"Xrd.InputSynth",
]

manual = [
	"Gio.Settings",
	"Graphene.Point",
	"Graphene.Point3D",
	"Graphene.Matrix",
	"Gxr.Context",
	"Gxr.Controller",
	"Gulkan.Client",
	"Gulkan.Texture",
	"Gdk.Event",
]

[[object]]
name = "Xrd.*"
status = "generate"
    [[object.function]]
    name = "button_set_text"
    ignore = true

[[object]]
name = "Xrd.Client"
status = "generate"
    [[object.signal]]
    name = "move-cursor-event"
    ignore = true

    [[object.signal]]
    name = "click-event"
    ignore = true

    [[object.signal]]
    name = "keyboard-press-event"
    ignore = true
